version: '3.5' 
services: 
  db: 
    image: postgres 
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgresql
    container_name: postgres-number-8
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - '${DB_PORT}:${DB_PORT}' 
  app: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: nest-number-8
    environment: 
      - PORT=${PORT} 
    ports: 
      - '3001:3001' 
    depends_on: 
      - db 
    volumes:
        - ./src:/app/src 
  pgadmin:
    image: dpage/pgadmin4 
    restart: always 
    container_name: pgadmin-number-8 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4 
    ports: 
      - '5050:80' 
    depends_on: 
        - db