services: 
  db: 
    image: postgres 
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres-poc
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - '${DB_PORT}:${DB_PORT}' 
  app: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: nest-poc
    env_file:
      - .env
    ports: 
      - '3001:3001' 
    depends_on: 
      - db 
    volumes:
        - ./src:/app/src 
    working_dir: /app
    command: sh -c "./scripts/wait-for-it.sh db:${DB_PORT} -- ./scripts/startup-dev.sh"
  pgadmin:
    image: dpage/pgadmin4 
    restart: always 
    container_name: pgadmin-poc 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4 
    ports: 
      - '5050:80' 
    depends_on: 
        - db